# Development Profile
spring.datasource.url=jdbc:mysql://localhost:3306/java?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=14263208@aA
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
logging.level.com.blogapp=DEBUG
